version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/api-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/command-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/system-rules-ingestor"
    schedule:
      interval: "weekly"
