export default {
    "RECORD_ALREADY_PUBLISHED": "Record is already published",
    "RECORD_NOT_FOUND": "Record does not exist in the system",
    "PROMETHEUS_DATASOURCE_NOT_FOUND": "Prometheus data source does not exist",
    "RULE_ALREADY_EXIST": "Alert Rule already exists",
    "RULE_ALREADY_PUBLISHED": "Alert Rule already published",
    "INVALID_MANAGER": "Invalid Alert manager",
    "UPDATE_FAILURE": "Failed to update record",
    "INVALID_QUERY": "Invalid Query",
    "RECORD_ALREADY_DELETED": "Record is already deleted",
    "FOLDER_NOT_FOUND": "Alert folder not found",
    "CATEGORY_NOT_EXIST": "Category does not exists",
    "UPDATE_STATUS_FAILURE": "Failed to update alert status",
    "WEBHOOK_MISSING": "webhook url is missing",
    "INTERNAL_SERVER_ERROR": "Internal Server Error",
    "DEFAULT_TEST_NOTIFICATION_MESSAGE": "Hello World",
    "METHOD_NOT_IMPLEMENTED": "method not implemented",
    "SILENCE_EXPIRED": "Silence is already expired",
    "ALERTS_NOT_RETIRED": "Failed to retire alerts for dataset",
    "ALERTS_FETCH_FAILURE": "Failed to fetch alerts for dataset",
    "ALERTS_RETIRED_SUCCESSFULLY": "Alerts retired successfully for datasets",
    "SILENCE_DELETED_SUCCESSFULLY":"Silence deleted successfully for the Alert rule",
    "ALERTS_PUBLISHED_SUCCESSFULLY": "Alerts published successfully for datasets",
    "ALERT_PUBLISH_FAILURE":"Failed to publish alerts for dataset",
    "ALERT_CREATE_FAILURE":"Failed to create alerts for datasets",
    "METRIC_ALIAS_CREATE_FAILURE":"Failed to create metric alias for datasets",
    "ALERTS_NOT_FOUND":"Alert rule does not exist",
    "METRIC_ALIAS_NOT_FOUND":"Metric alias does not exist",
    "METRIC_ALIAS_FETCH_FAILURE":"Failed to fetch alert metrics for dataset",
    "METRIC_ALIAS_NOT_DELETED": "Failed to delete matric alias for datasets",
    "METRIC_ALIAS_DELETED_SUCCESSFULLY":"Metric alias deleted successfully for datasets"
} 
