name: Build and Deploy
run-name: Workflow run for ${{ github.ref }}
on:
  push:
    branches:
      - main
      - develop
    tags:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-api-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::522814700227:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push to ECR
        run: |
          docker build -t 522814700227.dkr.ecr.us-east-1.amazonaws.com/obsrv_services_lms_sb_obsrv_api_service:${{ github.sha }} -f ./api-service/Dockerfile .
          docker tag 522814700227.dkr.ecr.us-east-1.amazonaws.com/obsrv_services_lms_sb_obsrv_api_service:${{ github.sha }} 522814700227.dkr.ecr.us-east-1.amazonaws.com/obsrv_services_lms_sb_obsrv_api_service:latest
          docker push 522814700227.dkr.ecr.us-east-1.amazonaws.com/obsrv_services_lms_sb_obsrv_api_service:${{ github.sha }}
          docker push 522814700227.dkr.ecr.us-east-1.amazonaws.com/obsrv_services_lms_sb_obsrv_api_service:latest

